config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  get 'bank_details/index'

  scope "(:locale)", locale: /en|zh|ko|/ do
    root 'posts#index'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/about' => 'about#index', :as => :about
  get '/news' => 'news#index', :as => :news
  get '/support' => 'supports#index', :as => :supports
  get '/support/submit_info' => 'supports#info_page',:as => :info_page
  get '/terms' => 'terms#index', :as => :terms
  get '/privacy' => 'privacy#index', :as => :privacy
  get '/contact' => 'contact#index', :as => :contact
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  # new route added by raman
  get '/welcome/activity_enj2' => 'welcome#activity_enj2', :as => :activity_enj2
  get '/welcome/activity_iotx' => 'welcome#activity_iotx', :as => :activity_iotx
  get '/welcome/vote' => 'welcome#vote', :as => :vote
  get '/welcome/activity_sky' => 'welcome#activity_sky', :as => :activity_sky
  get '/welcome/application_form' => 'welcome#application_form', :as => :application_form

  get '/email/verify' => 'token_expires#index', :as => :email_verify


  # new route added by raman
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/sessions/:id/clear_session/' => 'sessions#clear_existing_session', :as => :clear_session
  resource :support
  resource :member, :only => [:edit, :update]
  get 'userCenter/balance' => 'members#balance_summary', :as=> :balance_summary
  resource :identity, :only => [:edit, :update]
  get '/google_verifies/:id' => 'google_verifies#new', :as => :google_verifies
  post '/auth_google_verifies/:id' => 'google_verifies#create', :as => :create_google_verifies

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
    resources :two_factors, except: :destroy
  end

  resources :client_downloads , only: [:index]

  get '/documents/api_v2'
  get '/documents/websocket_api'

  scope module: :private do
    resources :bank_details
    # invite page referral
    match '/invite' => 'referral#invite', via: [:get, :post]
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: :index do
      collection do
        post 'sms_authentication'
        post 'google_authentication'
        post :send_token_sms
        get  :add_details
        post :create_bank_info

      end
    end
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end unless d.resource_name.eql?('fiats')
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history
    get '/history/download_csv' => 'history#download_csv', as: :download_csv_history
    get '/history/openOrders' => 'history#open_orders', as: :open_order_history

    get '/search/market' => 'markets#search', as: :search_market
    get '/show/market' => 'markets#show_all_markets', as: :show_all_markets
    get '/favorite/:id/:type' => 'markets#set_favorites'
    get '/market/prices' => 'markets#set_market_price'


    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        post :clear, on: :collection
      end
      resources :order_bids, :order_asks, :only => [:create] do
        post :clear, on: :collection
      end
    end

   post '/pusher/auth', to: 'pusher#auth'
  end

  scope ['', 'webhooks', ENV['WEBHOOKS_SECURE_URL_COMPONENT'].presence, ':ccy'].compact.join('/'), as: 'webhooks' do
    post 'tx_created', to: 'webhooks#tx_created'
    # post 'eth' => 'webhooks#eth'
  end

  draw :admin
  mount APIv2::Mount => APIv2::Mount::PREFIX

  namespace :test do
    resources :members, only: :index
  end unless Rails.env.production?


  get '/\*path' => redirect('/?goto=%{path}')
  match '*path' => redirect('/'), via: :get
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  auth_key :email
  attr_accessor :old_password, :description, :conditions

  MAX_LOGIN_ATTEMPTS = 5
  HUMANIZED_ATTRIBUTES = {
      :password_confirmation => "",
       email: '',
       password: '',
       conditions: ''
  }
  validates :email, presence: true, uniqueness: true, email: true

  validates :password, presence: true

  validates :password, length: { minimum: 8, maximum: 64}

  validates :password, format: { with: Rails.application.config.PASSWORD_FORMAT , multiline: true}

  validates :password_confirmation, presence: true

  validates :conditions, :acceptance => { :accept => '1', message: I18n.t('activerecord.error.messages.condition') }, on: :create

  before_validation :sanitize

  def increment_retry_count
    self.retry_count = (retry_count || 0) + 1
  end

  def too_many_failed_login_attempts
    retry_count.present? && retry_count >= MAX_LOGIN_ATTEMPTS
  end

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  private

  def sanitize
    self.email.try(:downcase!)
  end

end

app/controllers/authentications/identities_controller.rb
module Authentications
  class IdentitiesController < ApplicationController
    before_filter :auth_anybody!, only: :new
    # before_action :auth_member!

    def new
      # @identity = Identity.new(email: current_user.email)
      @identity = request.env['omniauth.identity'] || Identity.new
    end

    def edit
      @identity = current_user.identity
    end

    def update
      @identity = current_user.identity

      unless @identity.authenticate(params[:identity][:old_password])
        redirect_to edit_identity_path, alert: t('.auth-error') and return
      end

      if @identity.authenticate(params[:identity][:password])
        redirect_to edit_identity_path, alert: t('.auth-same') and return
      end

      if @identity.update_attributes(identity_params)
        current_user.send_password_changed_notification
        clear_all_sessions current_user.id
        reset_session
        redirect_to signin_path, notice: t('.notice')
      else
        render :edit
      end
    end


    def create
      identity = Identity.new(identity_params.merge(email: current_user.email))
      if identity.save && current_user.create_auth_for_identity(identity)
        redirect_to settings_path, notice: t('.success')
      else
        redirect_to new_authentications_identity_path, alert: identity.errors.full_messages.join(',')
      end
    end

    private

    def identity_params
      params.required(:identity).permit(:password, :password_confirmation)
    end

  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_filter :auth_anybody!, only: :new
  before_filter :auth_member! , except: :new
  layout 'landing'

  def new
    @identity = request.env['omniauth.identity'] || Identity.new
  end

  def edit
    @identity = current_user.identity
  end

  def update
    @identity = current_user.identity

    unless @identity.authenticate(params[:identity][:old_password])
      redirect_to edit_identity_path, alert: t('identities.update.auth-error') and return
    end

    if @identity.authenticate(params[:identity][:password])
      redirect_to edit_identity_path, alert: t('identities.update.auth-same') and return
    end

    if @identity.update_attributes(identity_params)
      current_user.send_password_changed_notification
      clear_all_sessions current_user.id
      reset_session
      redirect_to signin_path, notice: t('identities.update.notice')
    else
      render :edit
    end
  end

  private
  def identity_params
    params.required(:identity).permit(:password, :password_confirmation)
  end
end

app/views/identities/edit.html.erb
<section class="login_page">
  <div class="container">
    <div class="login_block">
      <div class="login_block_inner signup_block">
        <div class="login_logo"><a class="navbar-brand top_logo" href="<%= root_path %>"></a></div>
        <div class="login_hding"><span><%= t('.title') %></span></div>
        <div class="login_form pass_reset_sec">
          <%= render 'shared/flash' %>
          <%= simple_form_for @identity,:html=>{:onsubmit=>"return Validate(this);"} do |f| %>
            <span id="doc_type_error_msg" style="color:#a94442"></span>
            <%= f.input :old_password,:label =>  t('.old_password')  %>
            <%= f.input :password, :label => t('.new_password') %>
            <span id="doc_type_error_msg1" style="color:#a94442"></span>
            <%= f.input :password_confirmation,:label => t('.confirmation_password') %>
            <span id="doc_type_error_msg2" style="color:#a94442"></span>
            <%= f.button :wrapped, t('.update'),class: 'newbutton', cancel: settings_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  $( document ).ready(function() {
    $("[name='commit']").addClass('change_pwd');
    $('a.pull-right').addClass('reset_cancel');
    $('#identity_old_password').val("");
  });
  function Validate(oForm) {
      val = $('#identity_old_password').val();
      val1 =  $('#identity_password').val();
      val2 = $('#identity_password_confirmation').val();
      if (val == ''|| val1 == '' || val2 == ''){
          $('#doc_type_error_msg').text(" required filed can't be blank")
          return false
      }
  }

</script>

app/views/identities/new.html.erb
<% content_for :header do %> <span></span>
<% end %>
<% content_for :footer do %> <span></span>
<% end %>

<section class="login_page">
  <div class="container">
    <div class="login_block">
      <div class="login_block_inner signup_block">
        <div class="login_logo"><a href="<%= root_path %>" class="navbar-brand top_logo"></a></div>
        <div class="login_hding"><span><%= t('.heading') %></span></div>

        <div class="login_form">
          <%= render 'shared/flash'%>
          <%= simple_form_for @identity, url: '/auth/identity/register',defaults: { wrapper: false }  do |f| %>

            <div class="form-group">
              <div class="mail_fld form_row">
                <%= f.input :email, input_html: { name: 'email', autofocus: 'true', required:true, class:'input_fld'}, placeholder:t('.email'), label: false %>
                <span class="fld_icon">
                  <%= image_tag('pic_fillemail.png')%>
                </span>
              </div>
            </div>
            <div class="form-group">
              <div class="pass_fld form_row">
                <%= f.input :password, input_html: { name: 'password' ,class:'input_fld'},placeholder:t('.create_password'),label:false %>
                <span class="fld_icon">
                  <%= image_tag('pic_pwd.png')%>
                </span>
              </div>
            </div>
            <div class="form-group">
              <div class="pass_fld form_row">
                <%= f.input :password_confirmation, input_html: { name: 'password_confirmation',class:"input_fld" },placeholder:t('.confirm_password'),label:false %>
                <span class="fld_icon">
                  <%= image_tag('pic_pwd.png')%>
                </span>
              </div>
            </div>
            <div class="form-group">
              <div class="pass_fld form_row">
                <%= f.input :description, readonly: true, input_html: {name: 'description',class:"input_fld disabled", value: cookies[:ref]}, placeholder:t('.reference_user'), label:false%>
                <span class="fld_icon">
                  <%= image_tag('agent.png')%>
                </span>
              </div>
            </div>

            <%= hidden_field_tag 'register','1'%>
            <div class="form-group">
              <div class="checkbox" >
                <div class="my-check">
                  <%= f.input :conditions, as: :boolean, required: true, input_html: { name: 'conditions', class: 'terms' }, label:false%>
                  <label for="check1" class="lablel"><%= t('.agree_content') %> <span class="links"> <a class="" href="/terms" target="_blank"> <%= t('.terms') %> </a></span> </label>
                </div>

              </div>
            </div>

            <div class="form-group"style="margin-top: 12px;">
              <%= f.button :wrapped, t('.register'),class:'create_account grey_btn' %>
            </div>
            <div class="form-group">
              <span href="javascript:void(0)" style="text-align:right;width: 100%;float: left;"><%= t('.register_content') %>  <span class="links"> <%= link_to t('.login'),signin_path %></span></span>
            </div>
          <% end %>
        </div>
      </div>
    </div> <!--/.login_block-->
  </div>
</section>
<%= render 'shared/session_footer' %>
<%= content_for(:the_links) do %>
  I agree to the <%= link_to "Terms of Service", terms_path,:remote => true %>
  and <%= link_to "Privacy Policy", privacy_path, :remote => true %>
<% end %>

<script>
    $('#lang').on('click', function(){
        $(this).parent().toggleClass('open');
    });

    $(document).on('click', function(){
        $('#lang').parent().removeClass('open');
    });
    if($('#identity_conditions').parents('div.checkbox').find('span.error'))
    {
        $('#identity_conditions').parents('div.checkbox').find('span.error').css({'position': 'absolute', 'margin-top': '17px'});
    }
</script>