config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  get 'bank_details/index'

  scope "(:locale)", locale: /en|zh|ko|/ do
    root 'posts#index'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/about' => 'about#index', :as => :about
  get '/news' => 'news#index', :as => :news
  get '/support' => 'supports#index', :as => :supports
  get '/support/submit_info' => 'supports#info_page',:as => :info_page
  get '/terms' => 'terms#index', :as => :terms
  get '/privacy' => 'privacy#index', :as => :privacy
  get '/contact' => 'contact#index', :as => :contact
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  # new route added by raman
  get '/welcome/activity_enj2' => 'welcome#activity_enj2', :as => :activity_enj2
  get '/welcome/activity_iotx' => 'welcome#activity_iotx', :as => :activity_iotx
  get '/welcome/vote' => 'welcome#vote', :as => :vote
  get '/welcome/activity_sky' => 'welcome#activity_sky', :as => :activity_sky
  get '/welcome/application_form' => 'welcome#application_form', :as => :application_form

  get '/email/verify' => 'token_expires#index', :as => :email_verify


  # new route added by raman
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/sessions/:id/clear_session/' => 'sessions#clear_existing_session', :as => :clear_session
  resource :support
  resource :member, :only => [:edit, :update]
  get 'userCenter/balance' => 'members#balance_summary', :as=> :balance_summary
  resource :identity, :only => [:edit, :update]
  get '/google_verifies/:id' => 'google_verifies#new', :as => :google_verifies
  post '/auth_google_verifies/:id' => 'google_verifies#create', :as => :create_google_verifies

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
    resources :two_factors, except: :destroy
  end

  resources :client_downloads , only: [:index]

  get '/documents/api_v2'
  get '/documents/websocket_api'

  scope module: :private do
    resources :bank_details
    # invite page referral
    match '/invite' => 'referral#invite', via: [:get, :post]
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: :index do
      collection do
        post 'sms_authentication'
        post 'google_authentication'
        post :send_token_sms
        get  :add_details
        post :create_bank_info

      end
    end
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end unless d.resource_name.eql?('fiats')
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history
    get '/history/download_csv' => 'history#download_csv', as: :download_csv_history
    get '/history/openOrders' => 'history#open_orders', as: :open_order_history

    get '/search/market' => 'markets#search', as: :search_market
    get '/show/market' => 'markets#show_all_markets', as: :show_all_markets
    get '/favorite/:id/:type' => 'markets#set_favorites'
    get '/market/prices' => 'markets#set_market_price'


    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        post :clear, on: :collection
      end
      resources :order_bids, :order_asks, :only => [:create] do
        post :clear, on: :collection
      end
    end

   post '/pusher/auth', to: 'pusher#auth'
  end

  scope ['', 'webhooks', ENV['WEBHOOKS_SECURE_URL_COMPONENT'].presence, ':ccy'].compact.join('/'), as: 'webhooks' do
    post 'tx_created', to: 'webhooks#tx_created'
    # post 'eth' => 'webhooks#eth'
  end

  draw :admin
  mount APIv2::Mount => APIv2::Mount::PREFIX

  namespace :test do
    resources :members, only: :index
  end unless Rails.env.production?


  get '/\*path' => redirect('/?goto=%{path}')
  match '*path' => redirect('/'), via: :get
end

app/controllers/private/account_versions_controller.rb
module Private
  class AccountVersionsController < BaseController
    def index
      @account_versions_grid = AccountVersionsGrid.new(params[:account_versions_grid]) do |scope|
        scope.where(:member_id => current_user.id)
      end
      @assets = @account_versions_grid.assets.page(params[:page]).per(20)
    end
  end
end

app/controllers/private/api_tokens_controller.rb
module Private
  class APITokensController < BaseController
    before_action :auth_verified!

    def index
      @tokens = current_user.api_tokens
      ids = APIToken.select('max(id) as id')
      @access_tokens = APIToken.where(id: ids)
    end

    def new
      @token = current_user.api_tokens.build
    end

    def create
      @token = current_user.api_tokens.build api_token_params
      @token.scopes = 'all'

      if @token.save
        flash.now[:notice] = t('private.markets.show.success')
      else
        flash.now[:alert] = t('private.markets.show.error')
        render :new
      end
    end

    def edit
      @token = current_user.api_tokens.find params[:id]
    end

    def update
      @token = current_user.api_tokens.find params[:id]

      if @token.update_attributes(api_token_params)
        flash.now[:notice] = t('private.markets.show.success')
      else
        flash.now[:alert] = t('private.markets.show.error')
      end

      render :edit
    end

    def destroy
      @token = current_user.api_tokens.find params[:id]
      if @token.destroy
        redirect_to url_for(action: :index), notice: t('.success')
      else
        redirect_to url_for(action: :index), notice: t('.failed')
      end
    end

    private

    def api_token_params
      params.require(:api_token).permit(:label, :ip_whitelist)
    end

  end
end

app/controllers/private/assets_controller.rb
module Private
  class AssetsController < BaseController
    skip_before_action :auth_member!, only: [:index]

    def index
      @fiat_assets = Currency.assets(Koin.base_fiat_ccy.downcase)
      Currency.all.each do |ccy|
        name = ccy.fiat? ? :fiat : ccy.code.downcase.to_sym
        instance_variable_set :"@#{name}_proof", Proof.current(ccy.code.downcase.to_sym)
        if current_user
          instance_variable_set :"@#{name}_account", \
           current_user.accounts.with_currency(ccy.code.downcase.to_sym).first
        end
      end
    end

    def partial_tree
      account = current_user.accounts.with_currency(params[:id]).first
      @timestamp = Proof.with_currency(params[:id]).last.timestamp
      @json = account.partial_tree.to_json.html_safe
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/private/bank_details_controller.rb
module Private
  class BankDetailsController < BaseController
    before_action :find_bank, only: %i(show edit update destroy)

    def index
      @bank = current_user.bank_details
    end

    def new
      @bank = BankDetail.new
    end

    def create
      @bank = current_user.bank_details.new(bank_params)
      if @bank.save
        redirect_to bank_details_path
      else
        render 'new'
      end
    end

    def update
      if params[:ajax]
        result = @bank.update(active: true)
        render json: result
      else
        if @bank.update(bank_params)
          redirect_to bank_details_path
        else
          render 'edit'
        end
      end

    end

    def destroy
      @bank.destroy
      redirect_to bank_details_path
    end

    private

    def bank_params
      params.require(:bank_detail).permit(:name, :bank_name, :account_number, :ifsc_code, :active, :state, :member_id)
    end

    def find_bank
      @bank = BankDetail.find(params[:id])
    end
  end
end

app/controllers/private/base_controller.rb
module Private
  class BaseController < ::ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :check_email_nil
    before_filter :no_cache, :auth_member!

    private

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = Time.zone.now + 10.minutes #"Sat, 03 Jan 2009 00:00:00 GMT"
    end

    def check_email_nil
      redirect_to new_authentications_email_path if current_user && current_user.email.nil?
    end

  end
end

app/controllers/private/deposits/aokey7_tokens_controller.rb
module Private
  module Deposits
    class Aokey7TokensController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/base_controller.rb
module Private
  module Deposits
    class BaseController < ::Private::BaseController
      layout 'app'
      before_action :channel
      before_action :auth_activated!
      before_action :auth_verified!

      def channel
        @channel ||= DepositChannel.find_by_key(self.controller_name.singularize)
      end

      def model_kls
        "deposits/#{self.controller_name.singularize}".camelize.constantize
      end
    end
  end
end

app/controllers/private/deposits/bitcoin_cash_controller.rb
module Private
  module Deposits
    class BitcoinCashController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/cacplus_tokens_controller.rb
module Private
    module Deposits
      class CacplusTokensController < ::Private::Deposits::BaseController
        include ::Deposits::CtrlCoinable
      end
    end
  end
  

app/controllers/private/deposits/chelscoins_controller.rb
module Private
  module Deposits
    class ChelscoinsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/ecpplus_tokens_controller.rb
module Private
  module Deposits
    class EcpplusTokensController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/ems_tokens_controller.rb
module Private
  module Deposits
    class EmsTokensController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/eos_tokens_controller.rb
module Private
  module Deposits
    class EosTokensController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/ethereums_controller.rb
module Private
  module Deposits
    class EthereumsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/fiats_controller.rb
module Private
  module Deposits
    class FiatsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlBankable

      def create
        deposit = ::Deposits::Fiat.new(params_fiat_deposit)
        if deposit.save
          FiatAttachment.create(deposit_id: deposit.id, avatar: params[:deposit][:avatar])
        end
        render json: true
      end

      private

      def params_fiat_deposit
        params.require(:deposit).permit(:amount, :done_at, :currency, :fund_uid,).tap do |whitelisted|
          whitelisted[:account_id] = current_user.accounts.find_by_currency(params[:deposit][:currency])&.id
          whitelisted[:member_id] = current_user.id
          whitelisted[:fund_extra] = params[:deposit][:currency]
        end
      end

    end
  end
end

app/controllers/private/deposits/fto_tokens_controller.rb
module Private
  module Deposits
    class FtoTokensController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/impereums_controller.rb
module Private
  module Deposits
    class ImpereumsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/ripples_controller.rb
module Private
  module Deposits
    class RipplesController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/satoshis_controller.rb
module Private
  module Deposits
    class SatoshisController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/tronixes_controller.rb
module Private
  module Deposits
    class TronixesController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/views/private/settings/_authentication_disable.html.erb
<div class="modal" tabindex="-1" role="dialog" id="authModal">
  <div class="modal-dialog manage_add" role="document">
    <div class="modal-content ngdialog-content">
      <div class="modal-body">
        <div class="withdraw_disable">
          <div class="error_img"><img src="/jgicon.png" alt="img"></div>
          <p class="red_txt"><%=  t ('.auth_text') %></p>
          <p><%=  t ('.auth_text1') %></p>
          <div class="yzChoose">
            <a href="#" class="btgoogle redirect_setting"><span class="imgicon img-google1"></span><p class="ng-binding"><%=  t ('.google_auth') %></p></a>
            <a href="#" class="btphone redirect_setting" ><span class="imgicon img-phone"></span><p class="ng-binding"><%=  t ('.sms_auth') %></p></a>
          </div>
          <div class="smalltip">
            <span><%=  t ('.text') %></span>
            <a class="btn btn-orange" id="skipNow"><%=  t ('.skip_text') %></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/private/settings/_google_auth.html.erb
<div class="modal fade my_modal" id="two_factor">
  <%= simple_form_for :settings, url: google_authentication_settings_path, html: { class: 'form-inline' }  do |f| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title"><%= current_user.enable? ? t('.disable') :  t('.enable') %> <%= t('.google_title') %></h4>
        </div>
        <div class="modal-body">
          <% unless current_user.otp_module? %>
            <%#= current_user.email %>
            <%#= (current_user.provisioning_uri("Zinance.com"+" "+"(#{current_user})")) %>
            <% qr = RQRCode::QRCode.new(current_user.provisioning_uri("#{request.domain}"+" "+"(#{current_user.email})"), size: 10, level: :h ) %>
            <div class="qr_tbl">
              <table class="qr" align="center">
                <% qr.modules.each_index do |x| %>
                  <tr>
                    <% qr.modules.each_index do |y| %>
                      <% if qr.dark?(x,y) %>
                        <td class="black"/>
                      <% else %>
                        <td class="white"/>
                      <% end %>
                    <% end %>
                  </tr>
                <% end %>
              </table>
            </div>
          <% end %>
          <div class='verify_token tbl_div'>
            <div class='text-center tbl_cell'>
              <%= f.input_field :otp_code, placeholder: t('.Token_Verify'), class: 'form-control input-lg input_fld' %>
            </div>
            <div class="submit_btn_sec tbl_cell">
              <%= f.submit  t('.update'), class: 'btn btn-lg btn-block btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/private/settings/_refferal.html.erb
<div class="container-fluid inviteBanner">
  <% link_to '', invite_path , class: 'invite_anchor' %>
  <a href="/invite" class="invite_anchor"></a>
</div>

app/views/private/settings/_sms.html.erb
<div class="modal fade my_modal" id="sms_modal">
  <%= simple_form_for :settings, url: sms_authentication_settings_path, html: { class: 'form',:onsubmit=>"return Validate(this);" }  do |f| %>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><%= current_user.sms_enable? ? t('.disable') : t('.enable') %> <%=  t('.sms_title')%></h4>
            <span class="alert-danger hide" id="sms_error"><%= t('.sms_error_msg') %></span>
            <span class="alert-success hide" id="sms_success"><%= t('.sms_success_msg') %></span>
          </div>
          <div class="modal-body">
            <div class="form-group authentication_mdl">
              <label for="uname1"><%= t('.sms_label') %></label>
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 country-code-inputs">
                  <div class="country_code">
                    <% if current_user.sms_enable? %>
                      <% contact_num = current_user.contact_no_without_country_code %>
                      <%= f.input_field :contact_no, class: 'form-control form-control-lg rounded-0 bfh-phone', disabled: true, placeholder: contact_num.gsub(contact_num[2,5],'XXXXX') %>
                      <span class="country-code-names choose_country slct_drop_box" disabled="disabled">
                        <%= f.select :country_code, get_all_country_codes, selected: current_user.id_document.country_code || ENV['TWILLIO_REGION'] ,class:'form-control form-control-lg rounded-0 bfh-phone chosen-select', disabled: 'disabled' %>
                      </span>
                    <% else %>
                        <%= f.input_field :contact_no, class: 'form-control form-control-lg rounded-0 bfh-phone contact_validate target5'   %>
                        <span class="country-code-names choose_country slct_drop_box">
                          <%= f.select :country_code, get_all_country_codes, selected: (request.location.country_code || ENV['TWILLIO_REGION']), class:'form-control form-control-lg rounded-0 bfh-phone chosen-select ' %>
                        </span>
                    <% end %>
                  </div>
                </div>
              </div>
            <div>
          </div>
        </div>

        <div class="input-group form-group send_sms_block">
          <%= f.input_field :otp_code, placeholder: t('.sms_token'), class: 'form-control', style: 'height: 36px; width:calc(100% - 100px);' %>
          <span class="input-group-text"><%= link_to t('.sms_send1'), '#', id:'send_sms', class: 'btn btn-default btn-block' %></span>
        </div>

        <span id="name_error1" style="color:#a94442"></span>

        <div class="form-group text-center">
          <%= f.submit t('.sms_send') , class: 'btn btn-lg btn-block btn-primary' , id: 'sms_submit_btn' %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){

//    $( "#sms_submit_btn" ).click(function() {
//      if($('settings_contact_no').val().length > 10) {
//
//      } else {
//        // Disable submit button
//      }
//    });
    $(".contact_validate").keydown(function (e) {
      // Allow: backspace, delete, tab, escape, enter and .
      if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110]) !== -1 ||
          // Allow: Ctrl+A, Command+A
          (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
          // Allow: home, end, left, right, down, up
          (e.keyCode >= 35 && e.keyCode <= 40)) {
        // let it happen, don't do anything
        return;
      }
      // Ensure that it is a number and stop the keypress
      if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
        e.preventDefault();
      }
    });

  });
  $(".target5").keyup(function() {

      var maxChars = 15;
      if ($(this).val().length > maxChars) {
          $(this).val($(this).val().substr(0, maxChars));
          $('#name_error').text('  number is too long (maximum is 15 characters)')
      }
      else{ ( length > 0 &&  length <= 15 )
          $('#name_error').text("")
      }
  });

  function Validate(oForm) {

      var sms_enable = '<%= current_user.sms_enable? %>';
      if(sms_enable == 'true'){
          $('#name_error').text()
          return true
      }
      else if ($('.contact_validate').val().length == 0){
          $('#name_error').text('Please Enter Phone Number')
          return false
      }
      return true;

  }
</script>

app/views/private/settings/index.html.erb
<%#= render 'refferal' %>
<% if flash[:alert] %>
  <div class="container">
    <div class="flash-message">
      <div class="alert alert-dismissable alert-danger" style="margin-top: 10px">
        <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>
          <i class="fa fa-info-circle"></i>
          <span ><%= flash[:alert] %></span>
        </p>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/flash' %>
<% end %>

<div class="container">
  <div class="setting_wrapper">
  <div class="setting_wrap">
    <div class="setting_wrap_left">
      <div class="setting_blocks">
        <div class="setting_left_info">
          <div class="setting_left_info_icon">
            <span class="comn_icon icon1"></span>
          </div>

          <div class="setting_left_info_txt">
            <h4><%= t('.email.title') %></h4>
            <% if current_user.activated? %>
              <p class="text-ignore"><%= t('.email.description-activated') %></p>
            <% else %>
              <p class="text-ignore"><%= t('.email.description') %></p>
            <% end %>
          </div>
        </div>
        <div class="setting_right_info">
          <% if current_user.activated? %>
            <a href="#" class="btn btn-success btn-block disabled" role="button">
              <i class="fa fa-check-circle"></i>
              <span><%= t('.email.activated') %></span>
            </a>
          <% else %>
            <%= link_to t('.email.resend'), new_activation_path, class: 'btn btn-default btn-block' %>
          <% end %>
        </div>
      </div> <!--/.setting_blocks-->

      <div class="setting_blocks">
        <div class="setting_left_info">
          <div class="setting_left_info_icon">
            <span class="comn_icon icon2"></span>
          </div>
          <div class="setting_left_info_txt">
            <h4>
              <span><%= t('.verification.title') %></span>
              <i class="fa fa-bolt text-warning"></i>
            </h4>
            <p class="text-ignore"><%= t('.verification.description') %></p>
          </div>
        </div>

        <div class="setting_right_info">
          <% if current_user.id_document_verified? %>
            <a href="#" class="btn btn-success btn-block disabled" role="button">
              <i class="fa fa-check-circle"></i>
              <span><%= t('.verification.verified') %></span>
            </a>
          <% else %>
            <%= link_to t('.verification.go'), edit_id_document_path, class: 'btn btn-default btn-block' %>
          <% end %>
        </div>
      </div> <!--/.setting_blocks-->

      <div class="setting_blocks">
        <div class="setting_left_info">
          <div class="setting_left_info_icon">
            <span class="comn_icon icon3"></span>
          </div>
          <div class="setting_left_info_txt">
            <h4><%= t('.passwords.title') %></h4>
            <p class="text-ignore"><%= t('.passwords.description') %></p>
          </div>
        </div>
        <div class="setting_right_info">
          <% if current_user.identity %>
            <%= link_to t('.passwords.go'), edit_identity_path, class: 'btn btn-default btn-block' %>
          <% else %>
            <%= link_to t('.passwords.set'), new_authentications_identity_path, class: 'btn btn-default btn-block' %>
          <% end %>
        </div>

      </div> <!--/.setting_blocks-->

    </div>
    <div class="setting_wrap_right">
      <div class="setting_blocks">
        <div class="setting_left_info">
          <div class="setting_left_info_icon">
            <span class="comn_icon icon4"></span>
          </div>
          <div class="setting_left_info_txt">
            <h4><%= t('.google_authenticater.title') %></h4>
            <p class="text-ignore"><%= t('.google_authenticater.description') %></p>
          </div>
        </div>
        <div class="setting_right_info">
          <%= link_to "#{current_user.enable? ? t('.google_authenticater.disable') : t('.google_authenticater.enable')}",
                      '#two_factor',
                      data: { toggle: :modal },
                      class: 'btn btn-default btn-block enable_btn' %>
        </div>
      </div> <!--/.setting_blocks-->

      <div class="setting_blocks">
        <div class="setting_left_info">
          <div class="setting_left_info_icon">
            <span class="comn_icon icon5"></span>
          </div>
          <div class="setting_left_info_txt">
            <h4><%= t('.sms_authenticater.title') %></h4>
            <p class="text-ignore"><%= t('.sms_authenticater.description') %></p>
          </div>
        </div>
        <div class="setting_right_info">
          <%= link_to "#{current_user.sms_enable? ? t('.sms_authenticater.disable') : t('.sms_authenticater.enable')}",
                      '#sms_modal', data: { toggle: :modal },
                      class: 'btn btn-default btn-block enable_btn',id:'set_country_code' %>
        </div>
      </div> <!--/.setting_blocks-->
      <div class="setting_blocks">
        <div class="setting_left_info">
            <div class="setting_left_info_icon" style="max-width: 18% " >
              <%= image_tag('api_img.png') %>
            </div>

          <div class="setting_left_info_txt">
            <h4><%= t('.api_tokens.title') %></h4>
            <p class="text-ignore"><%= t('.api_tokens.description') %></p>
          </div>
        </div>
        <div class="setting_right_info">
          <%= link_to t('.api_tokens.go'), api_tokens_path, class: 'btn btn-default btn-block enable_btn' %>
        </div>
      </div>
    </div>

  </div>
</div>
</div>

<%= render partial: 'google_auth' %>
<%= render partial: 'sms', locals: {current_user: current_user} %>
<%= render partial: "authentication_disable" %>


<% content_for :guide_title do %>
  <h3>
    <i class="fa fa-user"></i>
    <span><%= current_user.email %></span>
  </h3>
<% end %>

<% content_for :guide do %>
  <ul class="list-group">
    <% if current_user.admin? %>
      <span class="label label-warning">ADMIN</span>
    <% end %>
  </ul>
  <p class="text-warning">
    <%= t('.safety_instruction').html_safe %>
  </p>
<% end %>


<script type="text/javascript">
    $(document).ready(function() {
        sms_enable = '<%= current_user.sms_auth? %>'
        google_enable = '<%= current_user.otp_module? %>'
//         if(sms_enable == 'false' &&  google_enable == 'false'){
//             $('#authModal').modal('show');
//         }

        $('#skipNow').click(function(){
            $('#authModal').modal('hide');
        });

        $('.redirect_setting').click(function(){
            window.location = "/settings";
        })

        $('#sms_modal').on('shown.bs.modal', function (e) {
            $('#settings_country_code').chosen();
        })
        $('#send_sms').click(function(e){
            e.preventDefault();
            mob_no = $("#settings_contact_no").val(),
            country_code= $("#settings_country_code").val(),
            $('#send_sms').addClass("disabled");
            <% if current_user.sms_enable? %>
              mob_no = '<%= current_user.contact_no_without_country_code %>'
            <% end %>

            if(!mob_no){
              $("#sms_error").html('Please fill the valid mobile number with country code');
              $("#sms_error").removeClass('hide');

            }

            else {
              $.ajax({
                type: "POST",
                url: '<%= send_token_sms_settings_path %>',
                data: { to: mob_no, code: country_code },
                dataType: 'script',
                  success: function(data){
                      $('#send_sms').removeClass("disabled");
                  },
                  complete: function(){
                }
              });
            }

        });

        $("#settings_contact_no").on('focus', function(){
          $("#sms_error").html('');
          $("#sms_success").addClass('hide');
        });
        $('#settings_country_code').on('change', function(){
        });
        <% if current_user.sms_enable? %>
          $('.country-code-inputs span select').attr('disabled', 'disabled')
        <% end %>
    });

</script>

app/views/private/settings/send_token_sms.js.erb
<% if @sms_status%>
  $("#sms_error").html('');
  $("#sms_error").html('Please check phone number. It is invalid, not able to send any sms');
  $("#sms_error").removeClass('hide');
  $('#sms_success').addClass('hide');
  $('#sms_success').fadeToggle(5000);
<% else %>
  $("#sms_error").addClass('hide');
  $('#sms_success').removeClass('hide');
  $('#sms_success').fadeToggle(5000);
<% end %>